### ISSUE TITLE
Filmer - Fetcha API

### ISSUE THREAD

**Issue by SpinalGlitter** [Nishune/Kino_Group_Project#15]
Som en utvecklare vill jag kunna hämta filmdata från ett API så att filmerna kan presenteras dynamiskt på sidan.

Given att det finns ett API som innehåller en lista med filmer
When utvecklaren anropar API:et med en GET-förfrågan
Then ska API:et returnera en JSON-struktur med information om filmerna
And datan ska innehålla fält med id, titel, genre, beskrivning, rekommenderad ålder, längd, bild.

Detta kort är beroende av att #9 är klart.

**Comment by LolloGro** [comment]
Har testat och det visar headline och film titel i enlighet med kod.
