### ISSUE TITLE
Filmer - DOM med JS

### ISSUE THREAD

**Issue by SpinalGlitter** [Nishune/Kino_Group_Project#20]
Som en utvecklare vill jag hämta data om filmer från ett API så att innehållet kan uppdateras utan att behöva hårdkodas.

Given att API:et är tillgängligt och innehåller filmdata
When sidan laddas i webbläsaren
Then ska JavaScript hämta filmerna från API:et och filmerna ska renderas dynamiskt som kort i HTML.

Detta kort är beroende av att kort #9 är klart så att datan finns att hämta och att kort #15 är klart så att det finns data att appenda. Kortet är även beroende av att kort #10 är klart så att det finns en container för filmerna.

**Comment by LolloGro** [comment]
Testat och filmer med test visas. När klickar på titel vissas ytterligare information om vald film.
