### ISSUE TITLE
Footer-DOM

### ISSUE THREAD

**Issue by Emilyempa** [Nishune/Kino_Group_Project#36]
**User Story**
Som användare vill jag kunna surfa in på sidan och hitta aktuell info i footer i en strukturerad ordning

**BDD**
Given att ett API har blivit fetchat
When webbsidan laddas
Then visas footer med all info från API

**Beroende**
Detta kort måste göras efter
#30 
#15 
#26 
och före
#51 
#24 

**Typ**
Del av Feature

**Comment by LolloGro** [comment]
Testat och information visas som det ska i footer.
